import type { QuestionResult, QuizQuestion } from "@/types";

export type ExamReportData = {
  documentName: string;
  courseName?: string | null;
  difficulty: string;
  score: number;
  total: number;
  percentage: number;
  elapsedSeconds: number;
  timeLimitSeconds: number;
  takenAt: string;
  results: QuestionResult[];
  questions: QuizQuestion[];
};

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}m ${s}s`;
}

export function buildExamReportText(data: ExamReportData): string {
  const lines: string[] = [
    "AcademiQ — Exam Report",
    "=".repeat(40),
    `Document: ${data.documentName}`,
    `Course: ${data.courseName || "—"}`,
    `Difficulty: ${data.difficulty}`,
    `Date: ${new Date(data.takenAt).toLocaleString()}`,
    `Time used: ${formatDuration(data.elapsedSeconds)} / ${formatDuration(data.timeLimitSeconds)}`,
    `Score: ${data.score} / ${data.total} (${data.percentage}%)`,
    "",
    "Question breakdown",
    "-".repeat(40),
  ];

  data.results.forEach((item) => {
    const q = data.questions[item.question_index];
    lines.push("");
    lines.push(`Q${item.question_index + 1}: ${q?.question ?? ""}`);
    lines.push(`Your answer: ${item.chosen || "—"}`);
    lines.push(`Correct answer: ${item.correct_answer}`);
    lines.push(`Result: ${item.correct ? "CORRECT" : "INCORRECT"}`);
    if (item.concept_tag) lines.push(`Concept: ${item.concept_tag}`);
    const explanation =
      item.explanation ||
      (q && "explanation" in q ? (q as QuizQuestion).explanation : "");
    if (explanation) lines.push(`Explanation: ${explanation}`);
    if (item.sources?.length) {
      lines.push("Sources:");
      item.sources.forEach((s) => {
        lines.push(`  - Chunk ${(s.chunk_index ?? 0) + 1}: ${s.excerpt}`);
      });
    }
  });

  lines.push("");
  lines.push("Generated by AcademiQ");
  return lines.join("\n");
}

export function downloadExamReport(data: ExamReportData, format: "txt" | "json") {
  const stamp = new Date(data.takenAt).toISOString().slice(0, 10);
  const base = `academiq-exam-${stamp}`;

  if (format === "json") {
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    triggerDownload(blob, `${base}.json`);
    return;
  }

  const blob = new Blob([buildExamReportText(data)], { type: "text/plain" });
  triggerDownload(blob, `${base}.txt`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
